/* Auto-generated by generate_wallpapers_payload.py */
#ifndef WALLPAPERS_PAYLOAD_H
#define WALLPAPERS_PAYLOAD_H

#include <stdint.h>
#include <stddef.h>

extern const uint8_t g_wall_under_construction_png[];
extern const uint64_t g_wall_under_construction_png_size;
extern const uint8_t g_wall_accurate_png[];
extern const uint64_t g_wall_accurate_png_size;
extern const uint8_t g_wall_bluescreen_png[];
extern const uint64_t g_wall_bluescreen_png_size;
extern const uint8_t g_wall_fallback_png[];
extern const uint64_t g_wall_fallback_png_size;
extern const uint8_t g_wall_meow_png[];
extern const uint64_t g_wall_meow_png_size;
extern const uint8_t g_wall_sparklymeow_png[];
extern const uint64_t g_wall_sparklymeow_png_size;
extern const uint8_t g_wall_sparklymeow_alt_png[];
extern const uint64_t g_wall_sparklymeow_alt_png_size;
extern const uint8_t g_wall_sparklymeow_altcircles_png[];
extern const uint64_t g_wall_sparklymeow_altcircles_png_size;
extern const uint8_t g_wall_sparklymeow_altlines_png[];
extern const uint64_t g_wall_sparklymeow_altlines_png_size;
extern const uint8_t g_wall_sparklymeow_altlines2_png[];
extern const uint64_t g_wall_sparklymeow_altlines2_png_size;

typedef struct {
    const char *filename;
    const uint8_t *data;
    uint64_t size;
} bundled_wallpaper_t;

#define NUM_BUNDLED_WALLPAPERS 10

static const bundled_wallpaper_t g_bundled_wallpapers[] = {
    { "Under Construction.png", g_wall_under_construction_png, 0 },
    { "accurate.png", g_wall_accurate_png, 0 },
    { "bluescreen.png", g_wall_bluescreen_png, 0 },
    { "fallback.png", g_wall_fallback_png, 0 },
    { "meow.png", g_wall_meow_png, 0 },
    { "sparklymeow.png", g_wall_sparklymeow_png, 0 },
    { "sparklymeow_alt.png", g_wall_sparklymeow_alt_png, 0 },
    { "sparklymeow_altcircles.png", g_wall_sparklymeow_altcircles_png, 0 },
    { "sparklymeow_altlines.png", g_wall_sparklymeow_altlines_png, 0 },
    { "sparklymeow_altlines2.png", g_wall_sparklymeow_altlines2_png, 0 },
};

static inline uint64_t get_bundled_wallpaper_size(int idx) {
    switch (idx) {
        case 0: return g_wall_under_construction_png_size;
        case 1: return g_wall_accurate_png_size;
        case 2: return g_wall_bluescreen_png_size;
        case 3: return g_wall_fallback_png_size;
        case 4: return g_wall_meow_png_size;
        case 5: return g_wall_sparklymeow_png_size;
        case 6: return g_wall_sparklymeow_alt_png_size;
        case 7: return g_wall_sparklymeow_altcircles_png_size;
        case 8: return g_wall_sparklymeow_altlines_png_size;
        case 9: return g_wall_sparklymeow_altlines2_png_size;
        default: return 0;
    }
}

#endif /* WALLPAPERS_PAYLOAD_H */
