#!/usr/bin/env python3
import os
import glob
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
REPO_ROOT = os.path.dirname(PROJECT_ROOT)
WALLPAPERS_DIR = os.path.join(REPO_ROOT, "Test-Media", "Wallpapers")

OUT_S = os.path.join(PROJECT_ROOT, "bin", "kernel", "wallpapers_payload.s")
OUT_H = os.path.join(PROJECT_ROOT, "include", "wallpapers_payload.h")

def sanitize(filename):
    s = re.sub(r'[^a-zA-Z0-9_]', '_', filename).lower()
    return f"g_wall_{s}"

def main():
    os.makedirs(os.path.dirname(OUT_S), exist_ok=True)
    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)

    files = sorted(os.listdir(WALLPAPERS_DIR))
    entries = []

    for f in files:
        full_path = os.path.join(WALLPAPERS_DIR, f)
        if os.path.isfile(full_path) and (f.endswith(".png") or f.endswith(".jpg") or f.endswith(".bmp")):
            sym = sanitize(f)
            # Use forward slashes for assembly .incbin
            rel_path = os.path.relpath(full_path, os.path.join(PROJECT_ROOT, "bin", "kernel")).replace("\\", "/")
            entries.append((f, sym, rel_path, full_path.replace("\\", "/")))

    # Write assembly file
    with open(OUT_S, "w", encoding="utf-8") as s_file:
        s_file.write(".section .rodata\n")
        for orig_name, sym, rel_path, abs_path in entries:
            s_file.write(f".global {sym}\n")
            s_file.write(f".global {sym}_size\n")
            s_file.write(f"{sym}:\n")
            s_file.write(f'    .incbin "{abs_path}"\n')
            s_file.write(f"{sym}_end:\n")
            s_file.write(f"{sym}_size:\n")
            s_file.write(f"    .quad {sym}_end - {sym}\n\n")

    # Write C header file
    with open(OUT_H, "w", encoding="utf-8") as h_file:
        h_file.write("/* Auto-generated by generate_wallpapers_payload.py */\n")
        h_file.write("#ifndef WALLPAPERS_PAYLOAD_H\n")
        h_file.write("#define WALLPAPERS_PAYLOAD_H\n\n")
        h_file.write("#include <stdint.h>\n#include <stddef.h>\n\n")

        for orig_name, sym, rel_path, abs_path in entries:
            h_file.write(f"extern const uint8_t {sym}[];\n")
            h_file.write(f"extern const uint64_t {sym}_size;\n")

        h_file.write("\ntypedef struct {\n")
        h_file.write("    const char *filename;\n")
        h_file.write("    const uint8_t *data;\n")
        h_file.write("    uint64_t size;\n")
        h_file.write("} bundled_wallpaper_t;\n\n")

        h_file.write(f"#define NUM_BUNDLED_WALLPAPERS {len(entries)}\n\n")
        h_file.write("static const bundled_wallpaper_t g_bundled_wallpapers[] = {\n")
        for orig_name, sym, rel_path, abs_path in entries:
            h_file.write(f'    {{ "{orig_name}", {sym}, 0 }},\n')
        h_file.write("};\n\n")

        h_file.write("static inline uint64_t get_bundled_wallpaper_size(int idx) {\n")
        h_file.write("    switch (idx) {\n")
        for i, (orig_name, sym, rel_path, abs_path) in enumerate(entries):
            h_file.write(f"        case {i}: return {sym}_size;\n")
        h_file.write("        default: return 0;\n")
        h_file.write("    }\n")
        h_file.write("}\n\n")
        h_file.write("#endif /* WALLPAPERS_PAYLOAD_H */\n")

    print(f"Generated {OUT_S} and {OUT_H} with {len(entries)} wallpapers.")

if __name__ == "__main__":
    main()
